### ISSUE TITLE
Fields in Dependency Container can not show on Index page

### ISSUE THREAD

**Issue by DuyenNguyen66** [alexwenzel/nova-dependency-container#11]
I used a select field - Parent name on DependencyContainer. The selected option can be shown on detail, but not on Index. Is that a bug?

```
          DependencyContainer::make([
                Select::make('Parent name', 'parent_id')
                    ->options(
                        \App\Models\Category::whereCode('column')
                            ->whereNull('parent_id')
                            ->pluck('name', 'id'))
                    ->displayUsingLabels()
                    ->showOnIndex()
            ])->dependsOn('code', 'column'),
```
**Detail**
![image](https://user-images.githubusercontent.com/37392541/199204396-04f30361-e0a8-4255-a880-145aa72c85e3.png)

**Index**
![image](https://user-images.githubusercontent.com/37392541/199204572-8630eea9-c366-4892-ab78-c10e3535eb6f.png)

**Comment by alexwenzel** [comment]
hi @DuyenNguyen66 

all fields inside a dependency container are NOT displayed on index.
you need to work around this fact.

e.g.

```
...
DependencyContainer::make([
    Select::make('Parent name', 'parent_id')
        ->options(
            \App\Models\Category::whereCode('column')
                ->whereNull('parent_id')
                ->pluck('name', 'id'))
        ->displayUsingLabels()
])->dependsOn('code', 'column'),

Select::make('Parent name ONLY for index', 'parent_id')
        ->options(
            \App\Models\Category::whereCode('column')
                ->whereNull('parent_id')
                ->pluck('name', 'id'))
        -> onlyOnIndex(),
...
```

**Comment by DuyenNguyen66** [comment]
Thank for your answer. I can handle like your answer, it's ok for now.
But I have another question. Can we use `rules`  method in a dependency container? I placed `rules ` method like picture but it's not working. 

Example:
![image](https://user-images.githubusercontent.com/37392541/202669682-d799eeaa-9588-4601-9f9f-41aea2bb5602.png)
