### ISSUE TITLE
Nova action's `validateFields` not called due overridden `ActionRequest`

### ISSUE THREAD

**Issue by ThaDaVos** [alexwenzel/nova-dependency-container#20]
Due the `ActionRequest` being overriden by this package, other packages or custom logic depending on the `validateFields` method in actions isn't working as it's no longer being called...

See:
https://github.com/alexwenzel/nova-dependency-container/blob/9d84febb5a3129ae712bb1c57e866daf79bbe81b/src/Http/Requests/ActionRequest.php#L20-L43

What would be the best approach to remedy this?

**Comment by ThaDaVos** [comment]
Created a PR with the simplest fix I could think of - only overiding the `ActionRequest` when neccesary:
https://github.com/alexwenzel/nova-dependency-container/pull/21

**Comment by alexwenzel** [comment]
thank you, i implemented this in my new version
