### ISSUE TITLE
Rules method in a dependency container

### ISSUE THREAD

**Issue by tovantiep** [alexwenzel/nova-dependency-container#22]
Can we use rules method in a dependency container? I placed rules method like picture but it's not working.

![image](https://user-images.githubusercontent.com/74131799/205215336-0eaef51a-3a1b-49dc-a8ed-cae0dce411fd.png)

**Comment by tovantiep** [comment]
@alexwenzel

**Comment by alexwenzel** [comment]
hi @tovantiep 

I already used `rules()` within my own project. should work. Only i did not checked with recent updates, if it still works. I will check.

**Comment by alexwenzel** [comment]
hi @tovantiep 

i cannot reproduce :( this code works for me

<img width="981" alt="image" src="https://user-images.githubusercontent.com/3659928/220080708-6dd51565-c93d-4221-8d27-033edec01960.png">

**Comment by tovantiep** [comment]
Thank for your answer.  It's ok for now
