### ISSUE TITLE
Cannot read properties of null (reading 'attribute')

### ISSUE THREAD

**Issue by Gertiozuni** [alexwenzel/nova-dependency-container#26]
I have a case of using this in a modal, and gives this error on js part, and it is due to the fact that `component.field` is `null` instead of `undefined`.

https://github.com/alexwenzel/nova-dependency-container/blob/1c1b863477db2ed14ac86835609bb54e92a1beea/resources/js/components/FormField.vue#L97

**Comment by alexwenzel** [comment]
thanks for helping
