### ISSUE TITLE
Generate new release that supports Laravel 11

### ISSUE THREAD

**Issue by devnicolas1** [alexwenzel/nova-dependency-container#43]
With [this PR](https://github.com/alexwenzel/nova-dependency-container/pull/42) being merged, the `master` branch can be installed correctly in a Laravel 11 application, but there is still no release to make this consistent.

What I'm currently doing is:

```json
"require": {
        "alexwenzel/nova-dependency-container": "dev-master#7fba3929f189a39c7a4664cde6e3e6a765065970",
```

Would be nice to have a release generated to keep things tidy

**Comment by devnicolas1** [comment]
@alexwenzel once again sorry for dropping a mention, just thought this would be a nice thing to mention since its still related to the Laravel 11 PR which was accepted yesterday.

Feel free to close the issue if you are not generating a new release for any given reason. Thats fine.

Cheers! :)

**Comment by MaxKorlaar** [comment]
Agreed, this'd be helpful to us too :)!

**Comment by alexwenzel** [comment]
thank you for noticing me. i created a new release and tagged it with 1.11

https://github.com/alexwenzel/nova-dependency-container/releases/tag/1.11

**Comment by MaxKorlaar** [comment]
Thank you very much!
